version: "3"
services:
  ksuite-acl:
    build: .
    image: bburgy/ksuite-acl:v0.6.2
    environment:
      - SECRET_KEY_BASE=<secret>
      - PHX_HOST=<host>
      - PORT=<port>
      - KDRIVE_ID=<id>
      - KSUITE_API_TOKEN=<token>
      - CALDAV_USERNAME=<username>
      - CALDAV_PASSWORD=<password>
      - CALDAV_SERVER=<server>
      - TIMEZONE=<tz>
    ports:
      - 4000:4000
